# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: DCdemo
on:
  # GitHub Actions 使用国际标准时间，与国内相差 16 小时，设置时注意避雷
  # 详细语法参见 https://www.runoob.com/linux/linux-comm-crontab.html
  #schedule:
   # - cron: '*/30 20-21 * * *'  # 此处设置为北京时间 4:00、4:30、5:00、5:30 共尝试四次
  watch:
    types: [started]  # 也可以通过手动对项目 star 来触发
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: install modules
        run: 'pip install tensorflow'
        

      - name: auto checkin
        run: python run.py
